
= La bibliographie
Amal ALSAYED
 
:toc: macro
:numbered:
:icons:
 
== La liste des articles : 
 
* Software Security Durability -> Journal of Computer Science and Technology. 
* Good, Bad and beautiful Software -> CEPIS.
* A systematic literature review on green Software metrics -> University Amesterdam.
* Durability challenges in Software Enginerring ->CrossTalk, The Journal of Defense Software Engineering.
* Lean ICT pour une sobriété numérique.
* What does sustainability mean in and for Software Engineering ? -> Conference. 
* What de programmers know about Software Energy consumption ? -> 
* Towards greener Software engineering using software analytics : A systematic mapping -> 43rd Euromicro Conference on Software Engineering and Advanced Applications.
* Sustainable Software Engineering : Process and Quality models, life cycle and social aspects -> 
* Sustainableility and Quality : icing on the cake -> University.
* Requirements : The key to sustainability -> 
* Green Software process based on sustainability dimensions : The empirrical investigation -> Conference.
* Ecologie et numérique -> Cnnumérique.
 

== Le journal et Green IT.fr : 
 * Apple condamné à 25 millions d’euros d’amende pour « pratique commerciale trompeuse par omission » -> Ouest France. 
 * Commown allonge la durée de vie des Fairphone 2 -> Green IT.fr.
 * Mise à jour logicielle : il est urgent de légiférer -> Green IT.fr.
 

== Les articles de l'université : 
 * Guide méthodologique ACV des logiciels -> GreenSpercotr. 
 * Improving the energy efficiency and the performance of an Android 7 core application -> GreenSperctor. 
 * Is software ‘‘green’’? Application development environments and energy
efficiency in open source applications.
* Harnessing Green IT: Principles and Practices.
* Sustainability design in requirements engineering: state of practice.
* Sustainable software products – towards assessment criteria for resource and energy efficiency.
* Sustainable software products—Towards assessment criteria for resource and energy efficiency.
* Interactions between environmental sustainability goals and software product quality: A mapping study.


== Résumer : 

* *Empreinte environnementale du numérique mondial GreenIT.fr Frédéric Bordage 2019* :

	. L’objectif de l’étude est d’évaluer l’empreinte environnementale du numérique mondial. L’unité fonctionnelle considérée est «utiliser le numérique mondial pendant un an».

	. Cette étude illustre les impactes numérique sur l'environnement sur 3 modèles de quantification d’impacts environnementaux (utilisateurs, réseaux, centres informatiques) sur une durée de 15 ans de 2010 à 2025.

	. Les quatre indicateurs ont  environnementaux ont été retenus :
		.. Épuisement des ressources abiotiques (ADP).
		.. Réchauffement global (GES).
		.. Bilan énergétique (EP).
		.. Tension sur l’eau douce (Eau).

	. L’étude a montré les impacte pour chaque indicateur par rapport les trois modèles (utilisateurs, réseaux, centres informatiques). 

	. Tous les matériels vont augmenter leurs impactes multiplier de 2 à 3 fois à 2025, mais les objets connectés vont avoir le plus impacte multiplier  5 fois à 2025, La croissance exponentielle du nombre d’objets connectés (de 1 milliard en 2010 à 48 milliards en 2025).

	. L’étude propose quelques recommandations et hypothèses :
	.. Les recommandations :
	Quelques mesures simples permettraient de réduire considérablement l’empreinte environnementale du numérique mondial à l’horizon 2030 :
		... Réduire le nombre d’objets connectés en favorisant leur mutualisation et leur substitution et en ouvrant leurs APIs.
		... Réduire le nombre d’écrans plats en les remplaçant par d’autres dispositifs d’affichage : lunettes de réalité augmentée / virtuelle, vidéo projecteurs LED, etc.
		... Augmenter la durée de vie des équipements en allongeant la durée de garantie légale, en favorisant le réemploi, et en luttant contre certaines formules d’abonnement.
		... Réduire les besoins des services numériques via leur écoconception. Mises en oeuvre dès 2010, ces 4 mesures auraient permis de réduire de 27 % à 52 % l’empreinte du numérique mondial sur la période observée (2010 à 2025). C’est à dire de maintenir l’empreinte 2025 du numérique à son niveau de 2018 malgré l’ajout de 1,1 milliard d’utilisateurs supplémentaires.

	.. Les  hypothèses : 
	2 fois moins d’objets connectés en 2025.
	Basculement de 50 % des grands écrans sur vidéo-projecteur LED.
	Augmentation de 30 % de la durée de vie des équipements utilisateurs sur 15 ans.
	Réduction des besoins serveurs d’un facteur 2.
	Réduction de la quantité de données transmises de 20 %.
	Augmentation de 40 % de la durée de vie des équipements utilisateurs sur 15 ans.

	. Au-delà des recommandations simples et faciles à mettre en oeuvre présentées ci-dessus, nous militons donc, notamment, pour  
	Le développement d’une « low-tech numérique ».
	Une articulation effective entre « low » et « high » tech numérique.
	Une écoconception radicale des services numériques.

	. Allonger la durée de vie.
	. Mutualisations.

* *Fabriquer un Mac Book émet 90 fois plus de CO2 que 1 an d’utilisation en France.  Frédéric Bordage. Le 9 novembre 2011. GreenIT.fr. 
https://www.greenit.fr/2011/11/09/fabriquer-un-mac-book-emet-90-fois-plus-de-co2-que-1-an-d-utilisation-en-france/* : 

	. L’objectif de l’article est : de comprendre quelle est l’étape qui émet le plus de CO2 : la fabrication ou l’utilisation ?
	. Le résultat de cette étude est : la fabrication d’un Mac Book Pro 15 pouces d’Apple émet l’équivalent de 82 à 104 années d’utilisation en France.
	. Ce constat est important pour deux raisons. D’une part, il confirme l’ordre de grandeur (70 ans d’utilisation en France) que nous avons obtenu avec l’Esprimo E9900 de Fujitsu.
	. D’autre part, ces chiffres démontrent que la réduction de l’empreinte écologique des équipements informatiques passe avant tout, en France, par l’allongement de la durée d’utilisation du matériel. Tout le contraire de ce que font les entreprises et les particuliers qui se concentrent sur les économies d’énergie en phase d’utilisation.  

* *Sobriété numérique : 7 bonnes résolutions pour 2020. Frédéric Bordage. Le 7 janvier 2020. GreenIT.fr
https://www.greenit.fr/2020/01/07/sobriete-numerique-7-bonnes-resolutions-pour-2020/?utm_source=newsletter&utm_medium=email&utm_campaign=greenitfr_les_actualites&utm_term=2020-01-09* : 

	. L’étude propose 7 bonnes résolutions :
	.. Du renouvellement tu te passeras.
	.. Les objets cassés tu répareras.
	.. Reconditionné tu achèteras.
	.. Tes déchets tu recycleras.
	.. Les appareils tu débrancheras.
	.. Vers la conception responsable de tes services numériques tu tendras.
	.. De la 5G tu te passeras.
	.. De la 5G tu te passeras.


* *Quelle est l’empreinte carbone d’un ordinateur ? Frédéric Bordage. Le 10 février 2011. GreenIT.fr
https://www.greenit.fr/2011/02/10/quelle-est-l-empreinte-carbone-d-un-ordinateur/*

* *Good, Bad and beautiful Software -> CEPIS* : 

. Les déffirence entre le *Green Software* et *Green Software Engineering*. 
. Les 3 factors : *Feasibility*, *Efficiency*, *Sustanianability*.

* *A systematic literature review on green software metrics : *
The main goal of this study is to describe and to classify metrics related to software *greenness* 
present in the software engineering literature. 
.Research questions : 
Q1 : What green metrics have been proposed in the Software Engineering literature ? 
Q2 : How green metrics can be classified ? 
.Metrics Type :
* *Energy* : an energy metric can be used to perform evaluations on software components, as well as it can be used to estimate software 
energy consumption at the architectural level. 
* *Performance* : to measure performance indices. (response time). Throughput metric is classified as performance type because it 
measure a performance index, that is the number of service requests served at a given time period. 
* *Utilization* : related to measurement of computing resources, such as hard disk, storage, memory, and I/O operations. 
* *Economic* : to evaluate or to estimate the costs of green policies  application, more simply, the costs of software development,
at any stage.
* *Performance/Energy* : is a hybrid type, measure both performance dimension and energy consumption, *Power Efficiency Metric*.
It is classified as Performance/Energy.  
* *Pollution* : the measurement of pollution generated by software usage or development. 
.Metric contexts : 
* *Application* : metrics that deal with software programs or pieces of code. also perform measurements related to the application 
lifecycle, from the design to the maintenance stage. *Computational Energy*. 
* *Architecture* : that are designed to estimate energy consumption at the design stage. *Distributed System Energy Consumption*.
* *Service* : that measure energy consumption generated by the execution and the development of software service. *Energy Efficiency*. 
* *Service Center* : contains all those metrics that measure the impact of service execution on a service center. *Service Center 
Energy Consumption*. 
* *Virtual Machine* : that are designed to estimate or to evaluate energy consumption generated by virtual machines. *Disk Energy Model*. 
* *Data Center* : all those metrics that perform measurements of the impact of data storing and retrieval on a data center. *Data Center
Energy Productivity (DCeP)*.
* *Embedded Software* : that are used to perform evaluations or estimations on software that interacts directly with the physical world.
* *Executed Instructions Count Measure (EIC)*. 
* *Server* : that perform measurements on the impact of application, service or data processing on a server machine.
* *Server Power Utilization*.
* *DBMS* : all those metrics that are designed to measure the energy cost of data storing and retrieving operations.
* *Aggregated Cost*.



