== La liste des articles : 
 
* Software Security Durability -> Journal of Computer Science and Technology. 
* Good, Bad and beautiful Software -> CEPIS.
* A systematic literature review on green Software metrics -> University Amesterdam.
* Durability challenges in Software Enginerring ->CrossTalk, The Journal of Defense Software Engineering.
* Lean ICT pour une sobriété numérique.
* What does sustainability mean in and for Software Engineering ? -> Conference. 
* What de programmers know about Software Energy consumption ? -> 
* Towards greener Software engineering using software analytics : A systematic mapping -> 43rd Euromicro Conference on Software Engineering and Advanced Applications.
* Sustainable Software Engineering : Process and Quality models, life cycle and social aspects -> 
* Sustainableility and Quality : icing on the cake -> University.
* Requirements : The key to sustainability -> 
* Green Software process based on sustainability dimensions : The empirrical investigation -> Conference.
* Ecologie et numérique -> Cnnumérique.
 

== Le journal et Green IT.fr : 
 * Apple condamné à 25 millions d’euros d’amende pour « pratique commerciale trompeuse par omission » -> Ouest France. 
 * Commown allonge la durée de vie des Fairphone 2 -> Green IT.fr.
 * Mise à jour logicielle : il est urgent de légiférer -> Green IT.fr.
 

== Les articles de l'université : 
 * Guide méthodologique ACV des logiciels -> GreenSpercotr. 
 * Improving the energy efficiency and the performance of an Android 7 core application -> GreenSperctor. 
 * Is software ‘‘green’’? Application development environments and energy
efficiency in open source applications.
* Harnessing Green IT: Principles and Practices.
* Sustainability design in requirements engineering: state of practice.
* Sustainable software products – towards assessment criteria for resource and energy efficiency.
* Sustainable software products—Towards assessment criteria for resource and energy efficiency.
* Interactions between environmental sustainability goals and software product quality: A mapping study.


== Résumer : 

* *Empreinte environnementale du numérique mondial GreenIT.fr Frédéric Bordage 2019* :

	. L’objectif de l’étude est d’évaluer l’empreinte environnementale du numérique mondial. L’unité fonctionnelle considérée est «utiliser le numérique mondial pendant un an».

	. Cette étude illustre les impactes numérique sur l'environnement sur 3 modèles de quantification d’impacts environnementaux (utilisateurs, réseaux, centres informatiques) sur une durée de 15 ans de 2010 à 2025.

	. Les quatre indicateurs ont  environnementaux ont été retenus :
		.. Épuisement des ressources abiotiques (ADP).
		.. Réchauffement global (GES).
		.. Bilan énergétique (EP).
		.. Tension sur l’eau douce (Eau).

	. L’étude a montré les impacte pour chaque indicateur par rapport les trois modèles (utilisateurs, réseaux, centres informatiques). 

	. Tous les matériels vont augmenter leurs impactes multiplier de 2 à 3 fois à 2025, mais les objets connectés vont avoir le plus impacte multiplier  5 fois à 2025, La croissance exponentielle du nombre d’objets connectés (de 1 milliard en 2010 à 48 milliards en 2025).

	. L’étude propose quelques recommandations et hypothèses :
	.. Les recommandations :
	Quelques mesures simples permettraient de réduire considérablement l’empreinte environnementale du numérique mondial à l’horizon 2030 :
		... Réduire le nombre d’objets connectés en favorisant leur mutualisation et leur substitution et en ouvrant leurs APIs.
		... Réduire le nombre d’écrans plats en les remplaçant par d’autres dispositifs d’affichage : lunettes de réalité augmentée / virtuelle, vidéo projecteurs LED, etc.
		... Augmenter la durée de vie des équipements en allongeant la durée de garantie légale, en favorisant le réemploi, et en luttant contre certaines formules d’abonnement.
		... Réduire les besoins des services numériques via leur écoconception. Mises en oeuvre dès 2010, ces 4 mesures auraient permis de réduire de 27 % à 52 % l’empreinte du numérique mondial sur la période observée (2010 à 2025). C’est à dire de maintenir l’empreinte 2025 du numérique à son niveau de 2018 malgré l’ajout de 1,1 milliard d’utilisateurs supplémentaires.

	.. Les  hypothèses : 
	2 fois moins d’objets connectés en 2025.
	Basculement de 50 % des grands écrans sur vidéo-projecteur LED.
	Augmentation de 30 % de la durée de vie des équipements utilisateurs sur 15 ans.
	Réduction des besoins serveurs d’un facteur 2.
	Réduction de la quantité de données transmises de 20 %.
	Augmentation de 40 % de la durée de vie des équipements utilisateurs sur 15 ans.

	. Au-delà des recommandations simples et faciles à mettre en oeuvre présentées ci-dessus, nous militons donc, notamment, pour  
	Le développement d’une « low-tech numérique ».
	Une articulation effective entre « low » et « high » tech numérique.
	Une écoconception radicale des services numériques.

	. Allonger la durée de vie.
	. Mutualisations.

* *Fabriquer un Mac Book émet 90 fois plus de CO2 que 1 an d’utilisation en France.  Frédéric Bordage. Le 9 novembre 2011. GreenIT.fr. 
https://www.greenit.fr/2011/11/09/fabriquer-un-mac-book-emet-90-fois-plus-de-co2-que-1-an-d-utilisation-en-france/* : 

	. L’objectif de l’article est : de comprendre quelle est l’étape qui émet le plus de CO2 : la fabrication ou l’utilisation ?
	. Le résultat de cette étude est : la fabrication d’un Mac Book Pro 15 pouces d’Apple émet l’équivalent de 82 à 104 années d’utilisation en France.
	. Ce constat est important pour deux raisons. D’une part, il confirme l’ordre de grandeur (70 ans d’utilisation en France) que nous avons obtenu avec l’Esprimo E9900 de Fujitsu.
	. D’autre part, ces chiffres démontrent que la réduction de l’empreinte écologique des équipements informatiques passe avant tout, en France, par l’allongement de la durée d’utilisation du matériel. Tout le contraire de ce que font les entreprises et les particuliers qui se concentrent sur les économies d’énergie en phase d’utilisation.  

* *Sobriété numérique : 7 bonnes résolutions pour 2020. Frédéric Bordage. Le 7 janvier 2020. GreenIT.fr
https://www.greenit.fr/2020/01/07/sobriete-numerique-7-bonnes-resolutions-pour-2020/?utm_source=newsletter&utm_medium=email&utm_campaign=greenitfr_les_actualites&utm_term=2020-01-09* : 

	. L’étude propose 7 bonnes résolutions :
	.. Du renouvellement tu te passeras.
	.. Les objets cassés tu répareras.
	.. Reconditionné tu achèteras.
	.. Tes déchets tu recycleras.
	.. Les appareils tu débrancheras.
	.. Vers la conception responsable de tes services numériques tu tendras.
	.. De la 5G tu te passeras.
	.. De la 5G tu te passeras.


* *Quelle est l’empreinte carbone d’un ordinateur ? Frédéric Bordage. Le 10 février 2011. GreenIT.fr
https://www.greenit.fr/2011/02/10/quelle-est-l-empreinte-carbone-d-un-ordinateur/*

* *Good, Bad and beautiful Software -> CEPIS* : 

. Les déffirence entre le *Green Software* et *Green Software Engineering*. 
. Les 3 factors : *Feasibility*, *Efficiency*, *Sustanianability*.

* *A systematic literature review on green software metrics : *
The main goal of this study is to describe and to classify metrics related to software *greenness* 
present in the software engineering literature. 
.Research questions : 
Q1 : What green metrics have been proposed in the Software Engineering literature ? 
Q2 : How green metrics can be classified ? 
.Metrics Type :
* *Energy* : an energy metric can be used to perform evaluations on software components, as well as it can be used to estimate software 
energy consumption at the architectural level. 
* *Performance* : to measure performance indices. (response time). Throughput metric is classified as performance type because it 
measure a performance index, that is the number of service requests served at a given time period. 
* *Utilization* : related to measurement of computing resources, such as hard disk, storage, memory, and I/O operations. 
* *Economic* : to evaluate or to estimate the costs of green policies  application, more simply, the costs of software development,
at any stage.
* *Performance/Energy* : is a hybrid type, measure both performance dimension and energy consumption, *Power Efficiency Metric*.
It is classified as Performance/Energy.  
* *Pollution* : the measurement of pollution generated by software usage or development. 
.Metric contexts : 
* *Application* : metrics that deal with software programs or pieces of code. also perform measurements related to the application 
lifecycle, from the design to the maintenance stage. *Computational Energy*. 
* *Architecture* : that are designed to estimate energy consumption at the design stage. *Distributed System Energy Consumption*.
* *Service* : that measure energy consumption generated by the execution and the development of software service. *Energy Efficiency*. 
* *Service Center* : contains all those metrics that measure the impact of service execution on a service center. *Service Center 
Energy Consumption*. 
* *Virtual Machine* : that are designed to estimate or to evaluate energy consumption generated by virtual machines. *Disk Energy Model*. 
* *Data Center* : all those metrics that perform measurements of the impact of data storing and retrieval on a data center. *Data Center
Energy Productivity (DCeP)*.
* *Embedded Software* : that are used to perform evaluations or estimations on software that interacts directly with the physical world.
* *Executed Instructions Count Measure (EIC)*. 
* *Server* : that perform measurements on the impact of application, service or data processing on a server machine.
* *Server Power Utilization*.
* *DBMS* : all those metrics that are designed to measure the energy cost of data storing and retrieving operations.
* *Aggregated Cost*.

'''


== Understanding Green Software Development: A Conceptual Framework :

* Although the actual figures may vary depending on the specific hardware platform, the impact of software over energy consumption is 
definitely relevant. Realizing this implies a change of mindset for the software engineering community.
*Firstly,* determining the responsibility of software means increasing the awareness of developers over the energy consumption 
caused by their applications. 
*Secondly,* a new perspective of software as hardware driver arises.

* As a matter of fact, it gives developers a way to elaborate a strategy by analysing the causes of energy consumption and also
to validate the efficacy of the formulated strategies by measuring their impact and effect.

* stakeholders who are interested to or affected by sustainability issues. They trigger the need for developing energy-efficient software.

* Main strategies: *Refactoring* and *Self-adaptation*.
* *The refactoring strategy* : It is focused on minimizing software instructions and code patterns that may cause higher energy usage.
* *The self-adaptation strategy* : has the main goal of creating an energy-aware application that is able to choose among different 
configurations, with respect to different scenarios and contexts, that we call “energy profiles”.

* ”white-box” i.e. code-level or instruction-level metrics, and ”black-box” i.e. runtime metrics, such as usage ratios of system 
resources (CPU, RAM, etc.). Of course, timing is an important factor: white-box models can be used to provide both an on-line (run-time)
and off-line (compile-time) estimation of the software impact, while black-box can only perform on-line because they rely on resource
usage data.

* In embedded systems, for example, we have observed that code-level constructs may have an observable impact over power consumption
only in some cases. However, as the system architecture becomes more complex, these models appear to be too fine-grained to describe 
the effect of software over power consumption. In these cases, a resource-usage based model might be more meaningful: initial work has 
successfully proven the correlation between indicators of hardware resources and the power consumption of a desktop computer system. 
As a matter of fact, most of the software power profiling tools commercially available are based upon these types of models.

* CPU is the most important component to monitor. And, metrics, such as memory usage and, more importantly, I/O operations, 
have a significant correlation with power consumption.

* Software applications may require the activation of high power-consuming peripherals (e.g. GPS modules, 3G and WiFi antennas) 
that significantly modify the consumption profile of the device.

* 1) these resources cannot be ignored by models and must be explicitly measured, 2) software developers need to be aware that 
decreasing the computational complexity of software applications is not enough to develop an energy-efficient application, but they 
need to adopt an holistic approach.

* *Refactoring:* adopt code level guidelines to improve energy efficiency Predictive models embed the knowledge about both the 
resources (e.g., CPU) that consume power and the activities (e.g.,disk transfers) that drive their consumption. 
As a consequence, the next step, from a developer perspective, is to identify those code patterns that imply high usage of those 
resources and activities.  implementation choices (at code, design or architectural level) that make the software execution less energy 
efficient.

* Clean up useless code and data. 
* Look for Immortals.
* Monitor the appropriate resources.
* Scenario driven refactoring.
* Reduce amount of data transferred.

* *Self-adaptation:* Green software by design : self-adaptation techniques are a good solution when you can draw your software’s 
architecture from scratch. The key idea is to provide different configurations of the same application that can be activated at 
different times in order to find the best trade-off between features provided and energy consumed.

* CONCLUSIONS : There is significant evidence that a growing share of green IT will be addressed by green software engineering.
From a management perspective, making software greener is a challenging task that involves complex tradeoffs among stakeholders. 
From a technical perspective, several tools and good practices are available, although they are not yet well integrated in an organic 
framework able to provide the software developers and designers a unifying view. We presented a conceptual framework that provides an 
high-level view over the possible operational strategies for developing greener software, by leveraging the information provided by 
power consumption models and power profiling tools. We identified and explained two such strategies, i.e. refactoring and self adaptation,
although other strategies, at technological or process level, can be plugged in the framework, provided that they have a measurable 
impact on power consumption. This fundamental condition is the natural consequence of one of the lesson learned in 45 years of software 
engineering: no improvement is possible without measurement.

== Software Security Durability : 

* Software security features must be integrated in every level of development of software.
* Software Security is a process to secure the software by its factors which are known as (C.I.A) that is Confidentiality, Integrity, and
Availability.
* Security of software take care two main issues which is mechanisms and design. Software security is a process to build
design and analysis of the software security. Security of software provides a method to secure software from unauthorized access
and malicious attacks. 
* The identified security factors are discussed below: 
** Confidentiality.
** Integrity.
** Authentication.
** Non-repudiation.
** Authorization.
** Availability.
** Survivability.
** Reliability.
** Auditability.
** Trustworthiness.
** Accountability. 
* Durability as a term is defined as follows: In the term of a machine or system durability is about the long
lastingness of machine, same as in software context durability is concerned with the timeliness of a software. Timeliness of a
software security is called durability.
* So here it is said that time dependencies of software security is a factor of security. It depends on software
attributes that how much software is secure; exactly the durability decides how long software will be secured.
For durability purposes, the most important.
* Durability of a software solution largely depends on its ability to address unpredictable future needs and that this in turn results
primarily from how a software application is engineered, on the underlying architect it uses.
* Security accent changed to survivability of the software. Availability, survivability and durability of software security are complement of each other.
Durability effects where we want to check out that how long software will work.
* Security attributes of software, defines that how much a software is secure but durability defines that for how long time, your software will be secured.
* The security of software can be achieved by controlling the durability of software.
* 
**Durability is the key factor of security has been identified.
** Durability, a key factor for security is a major cause of software
security issues.
** Durability can be controlled by proper adjustment of design
characteristics and relation among attributes of security at design
level.
* Durability is the major factor of security which defines how all attributes depends upon durability. Durability as a security factor 
will contribute in security of a software, if it is considered.

== Harnessing Green IT: Principles and Practices : 
* What are the key environmental impacts arising from IT? What are the major environmental IT issues that we must address? How can we 
make our IT infrastructure, products, services, operations, applications, and practices environmentally sound? What are the 
regulations or standards with which we need to comply? How can IT assist businesses and society at large in their efforts to improve 
our environmental sustainability.
* Electricity is a major cause of climate change, because the coal or oil that helps generate electricity also releases carbon 
dioxide, pollutants, and sulfur into the atmosphere.
* Reducing electric power consumption is a key to reducing carbon dioxide emissions and their impact on our environment and global 
warming.
* IT affects our environment in several different ways. Each stage of a computer’s life, from its production, throughout its use, 
and into its disposal, presents environmental problems.
* The increased number of computers and their use, along with their frequent replacements, make the environmental impact of IT a 
major concern. Consequently, there Green IT refers to environmentally sound IT.
* Green IT also strives to achieve economic viability and improved system performance and use, while abiding by our social and 
ethical responsibilities.
* Green IT spans a number of focus areas and  activities, including : 
**  Design for environmental sustainability. 
** Energy-efficient computing.
** Power management.
** Data center design layout and location.
** Server virtualization.
** Responsible disposal and recycling.
** Regulatory compliance.
** Green metrics assessment tools and methodology.
** Environment related risk mitigation.
** Use of renewable energy sources and eco-labeling of IT product.
* To build a greener environment, we must modify or abolish many old and familiar ways of doing things and discover new methods. 
* Green use. Reduce the energy consumption of computers and other information systems and use them in an environmentally sound manner.
* Green disposal. Refurbish and reuse old computers and properly recycle unwanted computers and other electronic equipment. 
* Green design. Design energy efficient and environmentally sound components, computers, servers, and cooling equipment. 
* Green manufacturing. Manufacture electronic components, computers, and other associated subsystems with minimal or no impact on the environment. 
* Using IT : Environmentally sound practices : 
** Reducing energy consumption by PCs. 
** Enabling power management features.
** Turning off the system when not in use. 
** Using screensavers. 
** Using thin-client computers. 
** Energy conservation.
** Eco-friendly design.
** Virtualization.
* Green computer design aims to reduce the environmental impact of computers by adopting new technologies and using new techniques 
and materials while balancing environmental compatibility with economic viability and performance. Green design is quickly becoming a 
necessary business practice. Many computer manufacturers are in the process of making green PCs using non toxic materials that consume 
less electrical power and are easily reassembled.
* Entreprise Green IT Strategy : 
** Tactical incremental approach.
** Strategic approach.
** Deep green approach.

== Les obsolescence Programmé : Pico : 
* L'obsolescence Programmé définie comme *L'ensemble des techninques par lesquelles un metteur sur le marché vise à réduire 
délibérément la durée de vie d'un produit pour en augmenter le taux de replacement.*
* Quatre barrières à la réparation : *Le coût*, *La distace*, *Le transport*, *La solution*.

== L'obsolescence ou les raisons du remplacement d'un bien durable : proposition d'une échelle de mesure : 
* Les définitions et travaux sur l'obsolescence évoluent selon l'angle d'approche :*obsolescence du point de vue du produit* :
baisse délibérée de la durée de vie d'un produit par le fabricant-obsolescence planifiée. *obsolescence du point de vue de l'usage* : 
raisons pour lesquelles l'usager se sépare d'un produit. Elle diffèrent également selon le type de fin de vie du produit. *obsolescence* 
*absolue* (fin de vie technique du produit). *obsolescence relative* (finde vie prématurée du produit).
* Cette littérature fait cependant ressortir trois types de raisons invoquées pour expliquer le rempalcement : 
** L'obsolescence économique. 
** L'obsolescence technologique.
** L'obsolescence psychologique associée aux tendances de la mode. 
* La littérature académique : 
** Une dimension économique liée au rapport qualité/ prix du produit (économie, qualité, fonction, défaillance, physique).
** Une dimension technoligique liée aux améliorations des characteristics du produit (technologie, gonction, insatifaction).
** Une dimension psychologique liée à l'image et aux changement de vie/ de besoins des consommateurs (désirabilit ou psychologie, 
style, durabilité symbolique, changement dans la vie du consommateur).
** Obsolescence par péremption, obsolescence écologique.

== What does Sustainability mean in and for Software Engineering? :

* The general definition of sustainability as “the capacity to endure” and sustainable development as “meeting the needs of the present 
without compromising the ability of future generations to meet their own needs.
* Define “green and sustainable software” such that “direct and indirect negative impacts on economy, society, human beings, and environment that result 
from development, deployment, and usage of the software (...) ha(ve) a positive effect on sustainable development”, and “Green and
Sustainable Software Engineering” such that the “negative and positive impacts on sustainable development (...) are continuously assessed, documented,
and used for a further optimization of the software product”.
* Which system shall be preserved in which function over which time horizon? These parameters are used in the following to set the context for the
sustainability aspects in software engineering.
* ASPECTS OF SUSTAINABILITY IN SOFTWARE ENGINEERING : 
** Development Process Aspect: Sustainability during the initial software development process means development with responsible use of ecological,
human, and financial resources.
** Maintenance Process Aspect: Sustainability of the software system during its maintenance period until replacement by a new system includes 
continuous monitoring of quality and knowledge management.
** System Production Aspect: Sustainability of the software system as product with respect to its use of resources for production is achieved,
for example, by using green IT principles, sustainably produced hardware components, and optimising the required logistics for assembly, etc.
** System Usage Aspect: Sustainability in the usage processes within the application domain triggered by the software system as product takes into
account responsibility for the environmental impact and designing green business processes.

== Green IT and Green IS: Definition of Constructs and Overview of Current Practices : 
Cité 67 fois researchgate.net
https://www.researchgate.net/profile/Fabian_Loeser/publication/267737651_Green_IT_and_Green_IS_Definition_of_Constructs_and_Overview_of_Current_Practices_Completed_Research_Paper/links/5458cd700cf2cf516483bb66.pdf


* Sustainable management is understood as a long-term process of simultaneously optimizing economic, environmental and social performance while taking 
natural resource restrictions into account, thus allowing for enduring business activities without compromising the needs of future generations.
* Three goals that must be considered by executives to advance the environmental sustainability of business firms: 1) pollution prevention, achieved
through minimization of waste and emissions; 2) product stewardship, addressed by consideration of stakeholder demands and optimization of product lifecycles;
3) sustainable development, accomplished through a reduction of the organization's environmental footprint and commitment to a long-term sustainability vision.
* 
The term Green refers to technologies and processes that are environmentally friendly, i.e., which have a lower negative impact on the natural environment
than conventional ones. The environmental impact of Green technologies refers to the environmental footprint during their lifecycle while the environmental
impact of green processes refers to the reduced need for input resources, decreased pollution, and the reuse of materials state that IT and IS are two
fundamentally different concepts. Information Technology (IT) refers to computer hardware, software, and peripheral equipment Information Systems (IS)
"is a broad concept that covers the technology components and human activities related to the management and employment process of technology within the
organization" the concept of IS covers various aspects: it comprises IT (such as physical servers, office computers and network devices) as well as shared
services (such as databases or storage), business applications (such as ERP systems), IT human resources (such as skills and knowledge), and IS-related
managerial capabilities for organizational processes and business transformation.

* Green IT practices : 
** Consideration of environmental criteria when purchasing IT equipment and services.
** Energy-efficient IT operations in data centers and in office environments.
** Environmentally-friendly practices referring to the disposal of IT equipment.

* Green IS :
** Reengineering of business and production processes.
** Implementation of IS-based environmental management systems (EMS).
** Innovations for environmental technologies in end user products and services.
** Tracking of resource demands and emissions of products and services (lifecycle analyses).

* That Green IT refers to the negative first-order environmental impact of information systems (manufacturing, use, and disposal of IT equipment),
whereas the concept of Green IS comprises as well the positive second-order impacts (greening of business and production processes) and third-order impacts
(reduced resource consumption, waste, and emissions during the lifecycle of end products and services).
* The concept of Green IT refers to measures and initiatives which decrease the negative environmental impact of manufacturing, operations, and disposal
of Information Technology (IT) equipment and infrastructure.
* The concept of Green IS refers to practices which determine the investment in, deployment, use and management of information systems (IS) in order
to minimize the negative environmental impacts of IS, business operations, and IS-enabled products and services.


== Durability Challenges in Software Engineering : 

* Serviceability of software can be defined as the conditions in which software is still useful or maintainable.
Serviceability of software should be durable as to achieve maintainability. Durability in aspect of software is the time period for which 
software is giving services.
* software durability is related to software serviceability and it has been pointed out that achieving durability may enhance the
serviceability of the software. 
* In software engineering, durability depends on four characteristics : 

** Trustworthiness is a kind of assurance that software will perform as expected.
** Human trust is defined as a willingness to rely on partner(software) in whom one has confidence.
** Dependability is an ability to deliver service that can justifiably be trusted.
** Usability is the degree of software that can be used by particular users to reach quantified results with effectiveness and satisfaction.

* Software durability is a term used to describe the usefulness of service-life of a software such as designing and construction with optimal maintenance.
* The term may also be used to describe the whole software development life cycle by comparing between the service life of the design and its
functional undesirability.
* The durability of software may be expressed as a function of service quality and service life of the development cycle.
* There are three important service quality thresholds associated with durability:

** The quantified quality, recognized by the software developer or minimum codes.
** The minimum acceptable quality indicating the need for replacement.
** Failure.

* The steps which form the process, which is effective in achieving durability when performed iteratively, incrementally,
and in parallel with the other activities, tasks, and primary objectives:

** To establish durability as a powerful factor of software quality
** Identification of threat models of durability for degradation mechanisms
** Develop a durability program plan that includes trustworthiness, human trust, usability and dependability
** Identify and investigate their potential sources
** Estimate the risks associated to durability for these respected assets
** Arrange them based on the degree of the negative impacts
** Identify and investigate the durable necessities of serviceability an arrangement as a benchmark for quality
** Identify new attributes to provide a secure service-life of software for a specific duration
** Identify durability subfactors and determine their impact on overall software
** Analyze software risks relating to durability
** Make an objective to lessen the complexity of software design by establishing durability as it optimize the maintainability
** Enhance quality of software by improving service-oriented design of software
** Calculate of durability parameters using available or developed calculation models
** Possible updation of the ordinary architectural design tools for durability

== Sustainability and Quality: icing on the cake :

* Software products mainly affect the environment through resource consumption that occurs during its use and production.
The most direct (and obvious) impact by a software product is energy consumption, but other resources may also have a negative impact on
the sustainability of the software. In this sense, the use of the processor, increased needs of memory and disk storage,
network utilization and bandwidth, potential relocation of software production and use, among others, are elements to take into account.
* Sustainable software development refers to a mode of software development in which resource use aims to meet product software needs
while ensuring the sustainability of natural systems and the environment.
* T HE R ESOURCES : energy consumption, software performance
depends on the basic computing resources like the CPU and the memory. To evaluate the software products sustainability in terms of
memory requirements and processor time. Other resources that appear in literature are network bandwidth and wireless technology. A few studies
evaluated the use of other types of resources that appear as a result of software product utilization: paper wastage, ink and toner costs, etc.
* the sustainability of a software product as the capacity of developing a software product in a sustainable manner.
* Software requirements can be classified into functional and non-functional requirements.
* the functional requirements are related  to  the  “What”  of  a  software  product.
* that non-functional quality requirements can be seen  as  the  “How”  of  a  software  product.
* So, based on the definitions of functional and non-functional requirements we believe that software sustainabilityis related to non-functional requirements.


== Circulaire du 3 décembre 2008 relative à l'exemplarité de l'Etat au regard du développement durable dans le fonctionnement de ses services et de ses
établissements publics.
https://www.legifrance.gouv.fr/affichTexte.do?cidTexte=JORFTEXT000020243534#JORFARTI000020243537
* Comment mettre en œuvre une politique Green IT ? greenit.fr 
https://www.greenit.fr/2009/11/27/comment-mettre-en-oeuvre-une-politique-green-it/

== Product Environmental Report 27-inch iMac with Retina 5K display 
Cet ordi nécessite 1 tonne de Co2 pour être produit. 
https://www.apple.com/environment/pdf/products/desktops/27-inch_iMac_with_Retina5KDisplay_PER_Mar2019.pdf 

== Pour une low-tech numérique 
https://www.greenit.fr/2019/09/24/%ef%bb%bfpour-une-low-tech-numerique/ 
* Plus les années passent et plus il apparaît évident que la low-tech est la seule voie possible pour construire la base de notre avenir numérique.
* l’intérêt de cette notion de low-tech numérique est surtout de structurer notre réflexion lorsque nous concevons les produits et les services numériques
de demain.


== Les différents types d'obsolescence 
http://ecomotion.overblog.com/les-diff%C3%A9rents-types-d-obsolescence

* Rapport d'information déposé en application de l'article 145 du Règlement par la mission d'information
sur la gestion durable des matières premières minérales. assemblee-nationale.fr
http://www.assemblee-nationale.fr/13/rap-info/i3880.asp
* Étude sur la durée de vie des équipements éléctriques et
éléctroniques. Juillet 2012. Agence de la transition écologique (ADEME). ademe.fr.
https://www.ademe.fr/sites/default/files/assets/documents/84636_duree_de_vie_des_eee.pdf



== MAITRISER LES RISQUES D’OBSOLESCENCE : ANTICIPER TO MANAGE OBSOLESCENCE RISKS: ANTICIPATE :

Dans le langage courant, un bien est dit obsolète lorsqu’il ne répond plus au besoin ou qu’il est techniquement dépassé.
Aujourd’hui, dans nos domaines industriels, un produit est obsolète lorsque nous sommes dans l’incapacité à approvisionner
ledit produit sur le marché, quelle qu’en soit la cause. L’obsolescence d’un composant ou d’une substance se caractérise donc
par le passage d’un état de disponibilité à l’achat vers un état d’indisponibilité à l’achat de la référence commerciale du produit
chez le fabricant, et ceci sur une période connue. L’obsolescence peut être définitive ou temporaire, intentionnelle ou
involontaire, partielle ou totale, officielle ou inavouée.
Les causes peuvent être nombreuses :
* Fabrication arrêtée :
** Evolution normative ou réglementaire / abandon de technologie,
** Rendement ou marché trop faible,
** Rupture d’approvisionnement de matières premières,
** Osolescence de l’outil de fabrication / test,
** Perte de compétence du fabricant.

* Commercialisation stoppée ou restrictive, voire dissuasive :
** Rentabilité trop faible,
** Changement de stratégie industrielle,
** Délai de livraison trop long, quantité imposée, prix de vente prohibitif, embargo, licence d’export, allocation.

Le cycle de vie traditionnel de tout produit commercial est le suivant :
* Introduction : initialisation, mise sur le marché
* Croissance et maturité ou stabilisation : commercialisation avec support associé
* Déclin : arrêt de commercialisation avec support personnalisé
* Retrait : plus aucune action du fournisseur


Depuis cette période, on observe un niveau toujours élevé du phénomène d’obsolescence des composants électroniques dû à
plusieurs raisons :
* Les technologies à l'état de l'art appartiennent dorénavant au domaine civil,
* Les durées de vie des composants sont en constante diminution en raison des besoins d’innovation de ces marchés (<
3 ans !),
* De nombreuses mutations technologiques (CMS, 5V à 1.5V, RoHS/DEEE, etc.) ;
* Des marchés cycliques avec surcapacité ou sous-capacité de productions (”nettoyage” des catalogues, fermeture
d’usines, etc).

Risques liés l’obsolescence

L’obsolescence est une occurrence probable pour tout produit commercial. L’obsolescence appartient aux événements pouvant
d’une part affecter la disponibilité opérationnelle d’un équipement et d’autre part avoir des conséquences sur les engagements
contractuels en termes calendaire et financier.
L’impact peut concerner le programme, l’industriel, le maître d'ouvrage, l’utilisateur ou toute combinaison de ceux-ci. Les cas
envisageables sont les suivants :
* Incapacité de l’industriel à fabriquer ou maintenir avec la performance requise dans la spécification de performance du
système. L’impact du risque peut se traduire pour le client par des restrictions d’emploi du système ou par la
diminution du taux de réussite dans la mission.
* Incapacité de l’industriel à fabriquer ou à maintenir dans les délais requis
* Incapacité de l’industriel à fabriquer ou maintenir dans les coûts définis. L’impact du risque peut se traduire par un
accroissement du coût d’acquisition pour le client ou par une réduction de la marge bénéficiaire pour le fournisseur.
Une bonne politique de management des risques constitue un paramètre clé des analyses préalables aux décisions tout au long
du cycle de vie des systèmes. Elle vise à fiabiliser le bon déroulement des opérations en mettant en œuvre des actions de
maîtrise des risques sur le triptyque « coût-délai-performance » et en consolidant la programmation financière.

Stratégie de gestion de l’obsolescence (IEC62402, 2007) :

* Stratégie passive
* Stratégie réactive
* Stratégie anticipative


==  Cycle de vie du logiciel

* l'Organisation internationale de normalisation (ISO), a défini en 1981 le logiciel (en anglais software) comme une création intellectuelle rassemblant des programmes, des procédures, des règles et de la documentation utilisés pour faire fonctionner un système informatique. Pour renforcer le caractère intellectuel dulogiciel, l'ISO précise en plus que le logiciel existe indépendemment des supports utilisés pour le transporter, ce qui sous-entend qu'il ne faut pas confondre le logiciel avec son support.
* Le génie logiciel cherche à établir et à utiliser des principes sains d'ingénierie dans le but de développer économiquement du logiciel qui satisfait les besoins, qui est fiable et qui fonctionne efficacement sur des machines réelles (d'après Fritz Bauer, 1969).
* En résumé, dans cette vue du génie logiciel, on peut dire que le résultat d'un procédé est un produit, et qu'un procédé est mis en oeuvre par des personnes qui utilisent des méthodes, techniques, outils et notations communs à la profession.
* le cycle de vie des logiciels : est la période de temps s'étalant du début à la fin du processus du logiciel. Il commence donc avec la proposition ou la décision de développer un logiciel et se termine avec sa mise hors service.
* Le cycle de développement du logiciel commence avec la décision de développer un logiciel et se termine avec la livraison du logiciel et son installation.


== What do programmers know about Software energy consumption ? 

* For mobile devices, energy consumption affects battery life and limits device use.
* For datacenters, energy consumption limits the number of machines that can be run and cooled.
* To reduce software energy consumption, programmers must start by measuring the energy consumption of their software.
* 


== Requirements: The Key to Sustainability :

* Sustainability is the capacity to endure, so a system’s sustainability describes how well it will continue to exist and function, even as
circumstances change.
* Software engineers tend to focus on sustainability’s technical dimension, in which it’s simply a measure of the software system’s longevity.
* we must ask which system to sustain, for whom, over which time frame, and at what cost. This involves five interrelated dimensions:

** The individual dimension covers individual freedom and agency (the ability to act in an environment), human dignity, and fulfillment.
It includes individuals’ ability to thrive, exercise their rights, and develop freely.
** The social dimension covers relationships between individuals and groups. For example, it covers the structures of mutual trust and communication in 
a social system and the balance between conflicting interests.
** The economic dimension covers financial aspects and business value. It includes capital growth and liquidity, investment questions, and financialoperations.
** The technical dimension covers the ability to maintain and evolve artificial systems (such as software) over time. It refers to maintenance and evolution,
resilience, and the ease of system transitions.
** The environmental dimension covers the use and stewardship of natural resources. It includes questions ranging from immediate waste production and energy
consumption to the balance of local ecosystems and climate change concerns.

