== Understanding Green Software Development: A Conceptual Framework :

* Although the actual figures may vary depending on the specific hardware platform, the impact of software over energy consumption is 
definitely relevant. Realizing this implies a change of mindset for the software engineering community.
*Firstly,* determining the responsibility of software means increasing the awareness of developers over the energy consumption 
caused by their applications. 
*Secondly,* a new perspective of software as hardware driver arises.

* As a matter of fact, it gives developers a way to elaborate a strategy by analysing the causes of energy consumption and also
to validate the efficacy of the formulated strategies by measuring their impact and effect.

* stakeholders who are interested to or affected by sustainability issues. They trigger the need for developing energy-efficient software.

* Main strategies: *Refactoring* and *Self-adaptation*.
* *The refactoring strategy* : It is focused on minimizing software instructions and code patterns that may cause higher energy usage.
* *The self-adaptation strategy* : has the main goal of creating an energy-aware application that is able to choose among different 
configurations, with respect to different scenarios and contexts, that we call “energy profiles”.

* ”white-box” i.e. code-level or instruction-level metrics, and ”black-box” i.e. runtime metrics, such as usage ratios of system 
resources (CPU, RAM, etc.). Of course, timing is an important factor: white-box models can be used to provide both an on-line (run-time)
and off-line (compile-time) estimation of the software impact, while black-box can only perform on-line because they rely on resource
usage data.

* In embedded systems, for example, we have observed that code-level constructs may have an observable impact over power consumption
only in some cases. However, as the system architecture becomes more complex, these models appear to be too fine-grained to describe 
the effect of software over power consumption. In these cases, a resource-usage based model might be more meaningful: initial work has 
successfully proven the correlation between indicators of hardware resources and the power consumption of a desktop computer system. 
As a matter of fact, most of the software power profiling tools commercially available are based upon these types of models.

* CPU is the most important component to monitor. And, metrics, such as memory usage and, more importantly, I/O operations, 
have a significant correlation with power consumption.

* Software applications may require the activation of high power-consuming peripherals (e.g. GPS modules, 3G and WiFi antennas) 
that significantly modify the consumption profile of the device.

* 1) these resources cannot be ignored by models and must be explicitly measured, 2) software developers need to be aware that 
decreasing the computational complexity of software applications is not enough to develop an energy-efficient application, but they 
need to adopt an holistic approach.

* *Refactoring:* adopt code level guidelines to improve energy efficiency Predictive models embed the knowledge about both the 
resources (e.g., CPU) that consume power and the activities (e.g.,disk transfers) that drive their consumption. 
As a consequence, the next step, from a developer perspective, is to identify those code patterns that imply high usage of those 
resources and activities.  implementation choices (at code, design or architectural level) that make the software execution less energy 
efficient.

* Clean up useless code and data. 
* Look for Immortals.
* Monitor the appropriate resources.
* Scenario driven refactoring.
* Reduce amount of data transferred.

* *Self-adaptation:* Green software by design : self-adaptation techniques are a good solution when you can draw your software’s 
architecture from scratch. The key idea is to provide different configurations of the same application that can be activated at 
different times in order to find the best trade-off between features provided and energy consumed.

* CONCLUSIONS : There is significant evidence that a growing share of green IT will be addressed by green software engineering.
From a management perspective, making software greener is a challenging task that involves complex tradeoffs among stakeholders. 
From a technical perspective, several tools and good practices are available, although they are not yet well integrated in an organic 
framework able to provide the software developers and designers a unifying view. We presented a conceptual framework that provides an 
high-level view over the possible operational strategies for developing greener software, by leveraging the information provided by 
power consumption models and power profiling tools. We identified and explained two such strategies, i.e. refactoring and self adaptation,
although other strategies, at technological or process level, can be plugged in the framework, provided that they have a measurable 
impact on power consumption. This fundamental condition is the natural consequence of one of the lesson learned in 45 years of software 
engineering: no improvement is possible without measurement.

== Software Security Durability : 

* Software security features must be integrated in every level of development of software.
* Software Security is a process to secure the software by its factors which are known as (C.I.A) that is Confidentiality, Integrity, and
Availability.
* Security of software take care two main issues which is mechanisms and design. Software security is a process to build
design and analysis of the software security. Security of software provides a method to secure software from unauthorized access
and malicious attacks. 
* The identified security factors are discussed below: 
** Confidentiality.
** Integrity.
** Authentication.
** Non-repudiation.
** Authorization.
** Availability.
** Survivability.
** Reliability.
** Auditability.
** Trustworthiness.
** Accountability. 
* Durability as a term is defined as follows: In the term of a machine or system durability is about the long
lastingness of machine, same as in software context durability is concerned with the timeliness of a software. Timeliness of a
software security is called durability.
* So here it is said that time dependencies of software security is a factor of security. It depends on software
attributes that how much software is secure; exactly the durability decides how long software will be secured.
For durability purposes, the most important.
* Durability of a software solution largely depends on its ability to address unpredictable future needs and that this in turn results
primarily from how a software application is engineered, on the underlying architect it uses.
* Security accent changed to survivability of the software. Availability, survivability and durability of software security are complement of each other.
Durability effects where we want to check out that how long software will work.
* Security attributes of software, defines that how much a software is secure but durability defines that for how long time, your software will be secured.
* The security of software can be achieved by controlling the durability of software.
* 
**Durability is the key factor of security has been identified.
** Durability, a key factor for security is a major cause of software
security issues.
** Durability can be controlled by proper adjustment of design
characteristics and relation among attributes of security at design
level.
* Durability is the major factor of security which defines how all attributes depends upon durability. Durability as a security factor 
will contribute in security of a software, if it is considered.

== Harnessing Green IT: Principles and Practices : 
* What are the key environmental impacts arising from IT? What are the major environmental IT issues that we must address? How can we 
make our IT infrastructure, products, services, operations, applications, and practices environmentally sound? What are the 
regulations or standards with which we need to comply? How can IT assist businesses and society at large in their efforts to improve 
our environmental sustainability.
* Electricity is a major cause of climate change, because the coal or oil that helps generate electricity also releases carbon 
dioxide, pollutants, and sulfur into the atmosphere.
* Reducing electric power consumption is a key to reducing carbon dioxide emissions and their impact on our environment and global 
warming.
* IT affects our environment in several different ways. Each stage of a computer’s life, from its production, throughout its use, 
and into its disposal, presents environmental problems.
* The increased number of computers and their use, along with their frequent replacements, make the environmental impact of IT a 
major concern. Consequently, there Green IT refers to environmentally sound IT.
* Green IT also strives to achieve economic viability and improved system performance and use, while abiding by our social and 
ethical responsibilities.
* Green IT spans a number of focus areas and  activities, including : 
**  Design for environmental sustainability. 
** Energy-efficient computing.
** Power management.
** Data center design layout and location.
** Server virtualization.
** Responsible disposal and recycling.
** Regulatory compliance.
** Green metrics assessment tools and methodology.
** Environment related risk mitigation.
** Use of renewable energy sources and eco-labeling of IT product.
* To build a greener environment, we must modify or abolish many old and familiar ways of doing things and discover new methods. 
* Green use. Reduce the energy consumption of computers and other information systems and use them in an environmentally sound manner.
* Green disposal. Refurbish and reuse old computers and properly recycle unwanted computers and other electronic equipment. 
* Green design. Design energy efficient and environmentally sound components, computers, servers, and cooling equipment. 
* Green manufacturing. Manufacture electronic components, computers, and other associated subsystems with minimal or no impact on the environment. 
* Using IT : Environmentally sound practices : 
** Reducing energy consumption by PCs. 
** Enabling power management features.
** Turning off the system when not in use. 
** Using screensavers. 
** Using thin-client computers. 
** Energy conservation.
** Eco-friendly design.
** Virtualization.
* Green computer design aims to reduce the environmental impact of computers by adopting new technologies and using new techniques 
and materials while balancing environmental compatibility with economic viability and performance. Green design is quickly becoming a 
necessary business practice. Many computer manufacturers are in the process of making green PCs using non toxic materials that consume 
less electrical power and are easily reassembled.
* Entreprise Green IT Strategy : 
** Tactical incremental approach.
** Strategic approach.
** Deep green approach.

== Les obsolescence Programmé : Pico : 
* L'obsolescence Programmé définie comme *L'ensemble des techninques par lesquelles un metteur sur le marché vise à réduire 
délibérément la durée de vie d'un produit pour en augmenter le taux de replacement.*
* Quatre barrières à la réparation : *Le coût*, *La distace*, *Le transport*, *La solution*.

== L'obsolescence ou les raisons du remplacement d'un bien durable : proposition d'une échelle de mesure : 
* Les définitions et travaux sur l'obsolescence évoluent selon l'angle d'approche :*obsolescence du point de vue du produit* :
baisse délibérée de la durée de vie d'un produit par le fabricant-obsolescence planifiée. *obsolescence du point de vue de l'usage* : 
raisons pour lesquelles l'usager se sépare d'un produit. Elle diffèrent également selon le type de fin de vie du produit. *obsolescence* 
*absolue* (fin de vie technique du produit). *obsolescence relative* (finde vie prématurée du produit).
* Cette littérature fait cependant ressortir trois types de raisons invoquées pour expliquer le rempalcement : 
** L'obsolescence économique. 
** L'obsolescence technologique.
** L'obsolescence psychologique associée aux tendances de la mode. 
* La littérature académique : 
** Une dimension économique liée au rapport qualité/ prix du produit (économie, qualité, fonction, défaillance, physique).
** Une dimension technoligique liée aux améliorations des characteristics du produit (technologie, gonction, insatifaction).
** Une dimension psychologique liée à l'image et aux changement de vie/ de besoins des consommateurs (désirabilit ou psychologie, 
style, durabilité symbolique, changement dans la vie du consommateur).
** Obsolescence par péremption, obsolescence écologique.

== What does Sustainability mean in and for Software Engineering? :

* The general definition of sustainability as “the capacity to endure” and sustainable development as “meeting the needs of the present 
without compromising the ability of future generations to meet their own needs.
* Define “green and sustainable software” such that “direct and indirect negative impacts on economy, society, human beings, and environment that result 
from development, deployment, and usage of the software (...) ha(ve) a positive effect on sustainable development”, and “Green and
Sustainable Software Engineering” such that the “negative and positive impacts on sustainable development (...) are continuously assessed, documented,
and used for a further optimization of the software product”.
* Which system shall be preserved in which function over which time horizon? These parameters are used in the following to set the context for the
sustainability aspects in software engineering.
* ASPECTS OF SUSTAINABILITY IN SOFTWARE ENGINEERING : 
** Development Process Aspect: Sustainability during the initial software development process means development with responsible use of ecological,
human, and financial resources.
** Maintenance Process Aspect: Sustainability of the software system during its maintenance period until replacement by a new system includes 
continuous monitoring of quality and knowledge management.
** System Production Aspect: Sustainability of the software system as product with respect to its use of resources for production is achieved,
for example, by using green IT principles, sustainably produced hardware components, and optimising the required logistics for assembly, etc.
** System Usage Aspect: Sustainability in the usage processes within the application domain triggered by the software system as product takes into
account responsibility for the environmental impact and designing green business processes.

== Green IT and Green IS: Definition of Constructs and Overview of Current Practices : 
Cité 67 fois researchgate.net
https://www.researchgate.net/profile/Fabian_Loeser/publication/267737651_Green_IT_and_Green_IS_Definition_of_Constructs_and_Overview_of_Current_Practices_Completed_Research_Paper/links/5458cd700cf2cf516483bb66.pdf


* Sustainable management is understood as a long-term process of simultaneously optimizing economic, environmental and social performance while taking 
natural resource restrictions into account, thus allowing for enduring business activities without compromising the needs of future generations.
* Three goals that must be considered by executives to advance the environmental sustainability of business firms: 1) pollution prevention, achieved
through minimization of waste and emissions; 2) product stewardship, addressed by consideration of stakeholder demands and optimization of product lifecycles;
3) sustainable development, accomplished through a reduction of the organization's environmental footprint and commitment to a long-term sustainability vision.
* 
The term Green refers to technologies and processes that are environmentally friendly, i.e., which have a lower negative impact on the natural environment
than conventional ones. The environmental impact of Green technologies refers to the environmental footprint during their lifecycle while the environmental
impact of green processes refers to the reduced need for input resources, decreased pollution, and the reuse of materials state that IT and IS are two
fundamentally different concepts. Information Technology (IT) refers to computer hardware, software, and peripheral equipment Information Systems (IS)
"is a broad concept that covers the technology components and human activities related to the management and employment process of technology within the
organization" the concept of IS covers various aspects: it comprises IT (such as physical servers, office computers and network devices) as well as shared
services (such as databases or storage), business applications (such as ERP systems), IT human resources (such as skills and knowledge), and IS-related
managerial capabilities for organizational processes and business transformation.

* Green IT practices : 
** Consideration of environmental criteria when purchasing IT equipment and services.
** Energy-efficient IT operations in data centers and in office environments.
** Environmentally-friendly practices referring to the disposal of IT equipment.

* Green IS :
** Reengineering of business and production processes.
** Implementation of IS-based environmental management systems (EMS).
** Innovations for environmental technologies in end user products and services.
** Tracking of resource demands and emissions of products and services (lifecycle analyses).

* That Green IT refers to the negative first-order environmental impact of information systems (manufacturing, use, and disposal of IT equipment),
whereas the concept of Green IS comprises as well the positive second-order impacts (greening of business and production processes) and third-order impacts
(reduced resource consumption, waste, and emissions during the lifecycle of end products and services).
* The concept of Green IT refers to measures and initiatives which decrease the negative environmental impact of manufacturing, operations, and disposal
of Information Technology (IT) equipment and infrastructure.
* The concept of Green IS refers to practices which determine the investment in, deployment, use and management of information systems (IS) in order
to minimize the negative environmental impacts of IS, business operations, and IS-enabled products and services.


== Durability Challenges in Software Engineering : 

* Serviceability of software can be defined as the conditions in which software is still useful or maintainable.
Serviceability of software should be durable as to achieve maintainability. Durability in aspect of software is the time period for which 
software is giving services.
* software durability is related to software serviceability and it has been pointed out that achieving durability may enhance the
serviceability of the software. 
* In software engineering, durability depends on four characteristics : 

** Trustworthiness is a kind of assurance that software will perform as expected.
** Human trust is defined as a willingness to rely on partner(software) in whom one has confidence.
** Dependability is an ability to deliver service that can justifiably be trusted.
** Usability is the degree of software that can be used by particular users to reach quantified results with effectiveness and satisfaction.

* Software durability is a term used to describe the usefulness of service-life of a software such as designing and construction with optimal maintenance.
* The term may also be used to describe the whole software development life cycle by comparing between the service life of the design and its
functional undesirability.
* The durability of software may be expressed as a function of service quality and service life of the development cycle.
* There are three important service quality thresholds associated with durability:

** The quantified quality, recognized by the software developer or minimum codes.
** The minimum acceptable quality indicating the need for replacement.
** Failure.

* The steps which form the process, which is effective in achieving durability when performed iteratively, incrementally,
and in parallel with the other activities, tasks, and primary objectives:

** To establish durability as a powerful factor of software quality
** Identification of threat models of durability for degradation mechanisms
** Develop a durability program plan that includes trustworthiness, human trust, usability and dependability
** Identify and investigate their potential sources
** Estimate the risks associated to durability for these respected assets
** Arrange them based on the degree of the negative impacts
** Identify and investigate the durable necessities of serviceability an arrangement as a benchmark for quality
** Identify new attributes to provide a secure service-life of software for a specific duration
** Identify durability subfactors and determine their impact on overall software
** Analyze software risks relating to durability
** Make an objective to lessen the complexity of software design by establishing durability as it optimize the maintainability
** Enhance quality of software by improving service-oriented design of software
** Calculate of durability parameters using available or developed calculation models
** Possible updation of the ordinary architectural design tools for durability

== Sustainability and Quality: icing on the cake :

* Software products mainly affect the environment through resource consumption that occurs during its use and production.
The most direct (and obvious) impact by a software product is energy consumption, but other resources may also have a negative impact on
the sustainability of the software. In this sense, the use of the processor, increased needs of memory and disk storage,
network utilization and bandwidth, potential relocation of software production and use, among others, are elements to take into account.
* Sustainable software development refers to a mode of software development in which resource use aims to meet product software needs
while ensuring the sustainability of natural systems and the environment.
* T HE R ESOURCES : energy consumption, software performance
depends on the basic computing resources like the CPU and the memory. To evaluate the software products sustainability in terms of
memory requirements and processor time. Other resources that appear in literature are network bandwidth and wireless technology. A few studies
evaluated the use of other types of resources that appear as a result of software product utilization: paper wastage, ink and toner costs, etc.
* the sustainability of a software product as the capacity of developing a software product in a sustainable manner.
* Software requirements can be classified into functional and non-functional requirements.
* the functional requirements are related  to  the  “What”  of  a  software  product.
* that non-functional quality requirements can be seen  as  the  “How”  of  a  software  product.
* So, based on the definitions of functional and non-functional requirements we believe that software sustainabilityis related to non-functional requirements.
* 























