:toc:
:toc: left
:toclevels: 3



= Chapitr II : 
Amal ALSAYED

== Définitions : 

* Client Léger (Thin Client en anglais) : est une interface utilisateur qui sert principalement à afficher des informations et à répondre aux interactions de
l'utilisateur. Peu ou pas de logique applicative réside sur le client (à part la vérification de base des entrées), la plupart du travail est effectué sur
un serveur central. [4]

* Client Lourd (Fat Client en anglais) : est une application client qui intègre une logique commerciale. Le traitement est donc décentralisé - le serveur
n'est responsable que de parties rudimentaires de la logique et sert principalement à stocker les données. [4]

== L'obsolescence programmée

Les définitions et travaux sur l’obsolescence évoluent selon l’angle d’approche : [3]

* *Obsolescence du point de vue du produit* : baisse délibérée de la durée de vie d’un produit par le fabricant-obsolescence planifiée.
* *Obsolescence du point de vue de l’usage* : raisons pour lesquelles l’usager se sépare d’un produit. Elle diffèrent également selon le type de fin de vie
du produit.
* *Obsolescence absolue* (fin de vie technique du produit). 
* *Obsolescence relative* (finde vie prématurée du produit). 

Selon [3], il existe trois types de raisons invoquées pour expliquer le remplacement : 

* L’obsolescence économique.
* L’obsolescence technologique.
* L’obsolescence psychologique associée aux tendances de la mode.






