:toc:
:toc: left
:toc-title: Plan



include::Remerciement.adoc[leveloffset=+1]
include::Introduction.adoc[leveloffset=+1]
include::Principes-et-Definitions.adoc[leveloffset=+1]
include::L-importance-du-couplage-entre-Software-et-Hardware.adoc[leveloffset=+1]
include::Les-cles-de-la-durabilité-de-logiciels-(Matrice).adoc[leveloffset=+1]


<<<
[bibliography]
== Bibliographie 
Amal ALSAYED

- [[[A,1]]] Fabian Loeser. Technische Universitaet Berlin. Green IT and Green IS: Definition of Constructs and Overview of Current Practices.
Cité 67 fois researchgate.net 
https://www.researchgate.net/profile/Fabian_Loeser/publication/267737651_Green_IT_and_Green_IS_Definition_of_Constructs_and_Overview_of_Current_Practices_Completed_Research_Paper/links/5458cd700cf2cf516483bb66.pdf[L'article]

- [[[B,2]]] S Murugesan.  2008 - ieeexplore.ieee.org. Harnessing Green IT: Principles and Practices. Cité 1318 fois. 
https://www.pitt.edu/~dtipper/2011/GreenPaper.pdf[L'article]

- [[[C,3]]] LOI n° 2015-992 du 17 août 2015 relative à la transition énergétique pour la croissance verte (1). Article 99. legifrance.gouv.fr. 
https://www.legifrance.gouv.fr/affichTexte.do;jsessionid=D07E4B7FF38C9264A5554513AB55B753.tplgfr22s_1?cidTexte=JORFTEXT000031044385&dateTexte=20200416[L'article]

- [[[D,4]]] Viktor C. Pavlu. 2003 – 2004. Thin-Client/Fat-Client Comparison. UNIVERSITY OF DERBY Derbyshire Business School. 
http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.132.6689&rep=rep1&type=pdf[L'article]

- [[[E,5]]] Luca FALVO. 2016. Haute École de Gestion de Genève (HEG-GE). Développements Natif, Xamarin, Hybride ou Web : Critères de choix et arbre de décision pour
un développement mobile. 
https://doc.rero.ch/record/278092/files/TDIG_Falvo_Luca.pdf[L'article]

- [[[F,6]]] Frédéric Bordage. GreenIT.fr. 2019. Empreinte environnementale du numérique mondial.
https://www.greenit.fr/wp-content/uploads/2019/10/2019-10-GREENIT-etude_EENM-rapport-accessible.VF_.pdf[L'article]

- [[[G,7]]] Christophe BOUILLON, Michel HAVARD. Rapport d'information déposé en application de l'article 145 du Règlement par la mission d'information
sur la gestion durable des matières premières minérales. assemblee-nationale.fr
http://www.assemblee-nationale.fr/13/rap-info/i3880.asp[L'article]

- [[[H,8]]] Shailendra Mudgal, Benoît Tinetti, Thibault Faninger, Sarah Lockwood, Gina Anderson. Étude sur la durée de vie des équipements éléctriques et
éléctroniques. Juillet 2012. Agence de la transition écologique (ADEME). ademe.fr.
https://www.ademe.fr/sites/default/files/assets/documents/84636_duree_de_vie_des_eee.pdf[L'article]


 



* « Programme / Logiciel ou Application », synonymes ou non ?. Apsynet.fr. 
https://www.apsynet.fr/programme-logiciel-ou-application-synonymes-ou-non/[L'article]

* Différents types de logiciel d'application. Microordinateur.blogspot.com
http://microordinateurr.blogspot.com/2012/11/differents-types-de-logiciel-d.html[L'article]

* La norme CEI 62402 utilise le mot « obsolète »