:toc:
:toc: left


= Introduction 
Amal ALSAYED 

Les industries, les conceptions et les technologies s'accélèrent et progressent considérablement à notre époque pour répondre aux besoins et aux conditions
préalables de l'homme, notamment la vitesse et le confort.

Comme nous le savons, ces progrès et cette augmentation ont des effets négatifs. L'un des impacts que nous combattons est l'impact environnemental.
Ces dernières années, nous avons constaté un grand changement dans le climat. Augmentation des températures et déshydratation dans certains endroits et
fonte de la neige dans d'autres. 

Il est clair que la technologie et les technologies de l'information contribuent à l'impact environnemental et au changement climatique par le biais de ses
produits qui ont un effet sur l'environnement pendant leur cycle de vie. La stratégie et la politique que les entreprises suivent pour réduire ces effets est
le *Green IT* tout au long du cycle de vie de leurs produits, depuis leur fabrication et leur utilisation jusqu'à leur élimination ou leur valorisation. 

Parce que ce cycle de vie est long et que chacune de ses étapes a un impact sur l'environnement, chaque étape a une stratégie pour faire face à ses effets.
C'est la raison pour laquelle l'étape d'utilisation a été choisi dans ce mémoire, car elle inclut le couplage entre *logiciels* et *matériels*. Par
conséquent, la question qui se pose à ce stade est la suivante : *Le logiciel et son cycle de vie font-ils vieillir le matériel (plus ou moins rapidement)
que le matériel ?* Ainsi, l'objectif de cette thèse est de mettre en place une matrice qui inclut les critères et les clés de la durabilité des logiciels.
Cette matrice nous permet de déterminer si un logiciel est durable ou non.

Ainsi, cette thèse consiste à clarifier tout point relatif au *logiciel* et au *matériel* dans la *durabilité* et à construire une définition de ce qu'est la
*durabilité*, afin qu'au final nous puissions évaluer les critères et les clés de la durabilité du logiciel sélectionné à *SmartPhone*.

Pour ce faire, nous nous pencherons d'abord sur les principes et les définitions afin de clarifier certains concepts et de déterminer l'empreinte écologique
du matériel informatique. Nous pourrons ensuite décrire l'importance du couplage entre le logiciel et le matériel informatique afin de pouvoir répondre à
notre question. Enfin, nous évaluerons la matrice de durabilité des logiciels pour SmartPhone.










