:toc:
:toc: left
:toc: right
:toc: preamble





= Introduction : 
Amal ALSAYED <amal.alsayed90@gmail.com>

== La notion de la Durabilité:

L'un des plus sujets courants dans ces nos jours est comment peut-on préservation de l'environnement ? et comment peut-on réduire la pollution, le gaz
à effet de serre et l'augmentation de la pourcentage du dioxyde de cabone dans l'air ?

Dans ce context, il est apparu le concept de la *Durabilité* parmi beaucoup des efforts qui sont faits. Dans les dernières années, on a remarqué que ce
concept soit appliqué dans plusieurs domaines comme l'immobilier et les équipements électroménagers. 

Evidemment, parmi ces domaines, il y a le domaine d'Informatique qui essaie en son tour de réduire ses négatives impacts sur l'environnement.

Alors, pour comprendre mieux *la notion de la durabilité*, on commence à distinguer les differences coceptes de le *Green IT* ou la *Gestion durable*,
*Green Technonlogie de l'Information* et *Green Système d'Information*.

La *Gestion durable* : est un processus qui est duré en long-temps pour optimiser l'économie, l'environnement et la sociale performance en prenant en copmte
les ressources naturelles. Ce proessus permet de continuer les business activites sans effectuer aux nouvelles générations. [1]

Avant d'illustrer les conceptes de la Technologie de l'Information et le Système d'Information, il faut bien marquer la difference entre eux. 
La *Technonlogie de l'Information* "Information Technologie" en anglais est fait référence au matériel informatique, aux logiciels et aux
équipements périphériques Information. Par contre le *Système d'Information* "Information System" en anglais est un concept large qui couvre les composantes
technologiques et les activités humaines liées au processus de gestion et d'emploi de la technologie au sein de l'organisation". 
Le concept de SI couvre divers aspects :

** Il comprend les TI (tels que les serveurs physiques, les ordinateurs de bureau et les dispositifs de réseau) ainsi que les services partagés
(tels que les bases de données ou le stockage).
** Les applications commerciales (telles que les systèmes ERP).
** Les ressources humaines en TI (telles que les compétences et les connaissances).
** Les capacités de gestion liées au SI pour les processus organisationnels et la transformation des activités. [1]

La *Green Technonlogie de l'Information* est les mesures et initiatives qui diminuent l'impact environnemental négatif de la fabrication,
de l'exploitation et de l'élimination des équipements et infrastructures des technologies de l'information. [1]

De cette concepte, les green IT pratiques :

** Prise en compte de critères environnementaux lors de l'achat de matériel et de services informatiques.
** Des opérations informatiques à faible consommation d'énergie dans les centres de données et les environnements de bureau.
** Pratiques respectueuses de l'environnement concernant l'élimination des équipements informatiques.

La *Green Système d'Information* est les pratiques qui déterminent l'investissement, le déploiement, l'utilisation et la gestion des systèmes d'information
(SI) afin de minimiser les impacts environnementaux négatifs des SI, des opérations commerciales et des produits et services basés sur les SI. [1]

De cette concept, les caractéristiques de la green SI : 

** Réingénierie des processus d'entreprise et de production.
** Mise en œuvre de systèmes de gestion de l'environnement (SGE) basés sur les SI.
** Innovations pour les technologies environnementales dans les produits et services destinés aux utilisateurs finaux.
** Suivi des demandes de ressources et des émissions de produits et de services (analyses du cycle de vie).





